version: '3.8'
services:
  room-db:
    image: mariadb:latest
    container_name: room-db
    ports:
      - "3306:3306" # 호스트 포트:컨테이너 포트
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: room-db
      MYSQL_USER: minguni
      MYSQL_PASSWORD: minguni
    volumes:
      - room-db-data:/var/lib/mysql # 데이터를 로컬에 영구 저장

volumes:
  room-db-data: