version: '3.8'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: room-service
    ports:
      - "8085:8080"
    depends_on:
      - room-db

  room-db:
    image: mariadb:latest
    container_name: room-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: room-db
      MYSQL_USER: minguni
      MYSQL_PASSWORD: minguni
    ports:
      - "3306:3306"

volumes:
  room-db-data: